version: 2

jobs:
  build:
    docker:
      - image: palantirtechnologies/circle-spark-base
    steps:
      - checkout
      - run: ./palantir/docker/publish-docker.sh
workflows:
  version: 2
  build:
    jobs:
      - build